In [40]:
import math
import numpy as np

פרק 1

In [18]:
math.factorial(6) 

720

In [1]:

leap_year = 0
for x in range(1500,2011):
    if(x % 4 == 0 and (x % 100 != 0 or x % 400 == 0)):
        leap_year=leap_year+1
print(leap_year)

124


In [38]:
def Srinivasa_Ramanujan(n):
    sum = 0
    for k in range(0,n+1):
        numerator = math.factorial(4*k)*(1103+26390*k)
        denominator = (math.factorial(k)**4)*(396**(4*k))
        sum += numerator / denominator
    return (2*math.sqrt(2)/9801) * sum

totle = 1 / Srinivasa_Ramanujan(0)
print(totle)
totle = 1 / Srinivasa_Ramanujan(1)
print(totle)


3.1415927300133055
3.1415926535897936


In [42]:
is_it = False
for k in np.arange(math.pi,math.pi/6,-0.01):
    if((math.sin(k)**2) + (math.cos(k)**2) == 1):
        is_it = True
    else:
        is_it = False
print(is_it)

True


In [43]:
math.sin(math.degrees(87))

0.8275467546646788

In [45]:
P = False
Q = True

P and Q or P and (not Q)

False

In [52]:


rez_part1 = (math.e)**2 * 2 * math.sin(math.pi/6)
rez_part2 = math.log(3)*math.cos(math.pi/9)
rez = rez_part1 + rez_part2 * math.log(3) - 5**3
print(rez)


-116.47678286892855


In [54]:
p = 1
q = 1
a = 10
b = 25

print((not p) and (not q))

print((a < b) and (a := b))

False
25


פרק 2

In [61]:
x = 10
y = 3
u = x + y
v = x*y
w = x/y
z = math.sin(x)
r = 8*math.sin(x) 
s = 5*math.sin(x*y)
p = x**y

print(type(u))
print(type(v))
print(type(w))
print(type(z))
print(type(r))
print(type(s))
print(type(p))

<class 'int'>
<class 'int'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'int'>


In [63]:
s = '123'
print(type(s))
n = float(s)
print(type(n))

<class 'str'>
<class 'float'>


In [68]:
s1 = 'HELLO'
s2 = 'hello'
print(s1 == s2)
print(s1.lower() == s2)
print(s1 == s2.upper())

False
True
True


In [86]:
word1 = 'Engineering'
word2 = 'Book'
print ("The world %s has %d  letters" % (word1,len(word1)))
print("The world %s has %d  letters" % (word2,len(word2)))

The world Engineering has 11  letters
The world Book has 4  letters


In [89]:

s = 'Python is great!'
w = 'Python'
print(w in s)

True


In [92]:
s = 'Python is great!'
x = s.split()
a = x[2]

print(a)

great!


In [95]:


list_a = [1, 8, 9, 15]
list_a.insert(1,2)
list_a.append(4)


print(list_a)
list_a.sort()
print(list_a)

[1, 2, 8, 9, 15, 4]
[1, 2, 4, 8, 9, 15]


In [97]:
array = np.linspace(-10,10,100)
print(array)

[-10.          -9.7979798   -9.5959596   -9.39393939  -9.19191919
  -8.98989899  -8.78787879  -8.58585859  -8.38383838  -8.18181818
  -7.97979798  -7.77777778  -7.57575758  -7.37373737  -7.17171717
  -6.96969697  -6.76767677  -6.56565657  -6.36363636  -6.16161616
  -5.95959596  -5.75757576  -5.55555556  -5.35353535  -5.15151515
  -4.94949495  -4.74747475  -4.54545455  -4.34343434  -4.14141414
  -3.93939394  -3.73737374  -3.53535354  -3.33333333  -3.13131313
  -2.92929293  -2.72727273  -2.52525253  -2.32323232  -2.12121212
  -1.91919192  -1.71717172  -1.51515152  -1.31313131  -1.11111111
  -0.90909091  -0.70707071  -0.50505051  -0.3030303   -0.1010101
   0.1010101    0.3030303    0.50505051   0.70707071   0.90909091
   1.11111111   1.31313131   1.51515152   1.71717172   1.91919192
   2.12121212   2.32323232   2.52525253   2.72727273   2.92929293
   3.13131313   3.33333333   3.53535354   3.73737374   3.93939394
   4.14141414   4.34343434   4.54545455   4.74747475   4.94949495
   5.151515

In [100]:
arrayA = np.array([-1, 0, 1, 2, 0, 3])
arrayB = arrayA[arrayA > 0]
print(arrayB) 

[1 2 3]


In [115]:
A = np.array([[3,5,3],[2,2,5],[3,8,9]])
t = A.T
print(t)

[[3 2 3]
 [5 2 8]
 [3 5 9]]


In [118]:
Z = np.zeros((2,4))
print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [121]:
Z = np.zeros((2,4))
Z[:,1] = 1
print(Z)

[[0. 1. 0. 0.]
 [0. 1. 0. 0.]]


In [122]:
%reset -f